### ISSUE TITLE
Query in stateChangeUrl

### ISSUE THREAD

**Issue by shekhar-patil27** [Mikuu/Pact-JVM-Example#2]
Hi, there!

Thanks for creating this pact example which is really helpful to understand PACT tool. I have a query in "stateChangeUrl" concept, as I am not aware about any other way on how to communicate over the GitHub I am putting my query as a Issue here; sorry about that.

I have re-implemented the above example by using maven (as more familiar with maven).  Done all the required changes. Successfully created pact file by executing a unit test.

I am using "pact-jvm-provider-maven" at provider side to verify pact. Mentioned appropriate <stateChangeUrl>http://localhost:8093/pactStateChange</stateChangeUrl>.

 When I am executing pact verification for pact file ConsumerNanohaWithNationality-ExampleProvider.json & ConsumerNanohaNoNationality-ExampleProvider.json, the verification passes for ConsumerNanohaWithNationality-ExampleProvider.json however it fails for  ConsumerNanohaNoNationality-ExampleProvider.json as it is not changing the state (not setting nationality to "null"). I have also observed it is also not printing the statements from the function "providerState".

Even if I comment out "PactController" class the verification for "ConsumerNanohaWithNationality-ExampleProvider.json" passes. 

It would be really helpful if you could help me to understand following pints

1) How "stateChangeUrl" logic works at pact side 
2) How the data gets pass in "POST" request for stateChangeUrl
3) How to get state from PACT file.

Please correct me if I am missing something here.

Thanks,
Shekhar

**Comment by shekhar-patil27** [comment]
Thanks for your detailed reply, it was really helpful to debug. I am able to execute the example in maven after doing following modification at my end
1) Downgrade pact version to V2
2) I think if we pass the null provider state then it's not getting pass in the request body, so I have changed state to non empty string  .given("")  to .given ("test") & changed switch case to have "default" value. 
              
          default:
                Nationality.setNationality("Japan");
                System.out.println("Pact Sate Change >> set default nationality ...");
                break;

With above changes the tests are executing properly now.

Thanks,
Shekhar

**Comment by Mikuu** [comment]
Hi Shekhar,

Actually, the value to `nationality` is already initialized as `Japan`. So, even if you don't set state value to `test`, `nationality` would also has the value of `Japan`.

Anyway, it good to make it's working. 👍 

BR.
Mikuu
