### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JoaoGFarias** [Mikuu/Pact-JVM-Example#5]
Thanks for this great example of Pact in JVM.

I have a question regarding which license this code is supposed to be under. I couldn't find a file with the license. It would be good in order to give a clear scope of usage of the code here.

**Comment by Mikuu** [comment]
Hi JoaoGFarias,

Thanks for the reminder, MIT license is now added.

BR.
Mikuu

**Comment by Mikuu** [comment]
close
